
drinkingKeywords = ['drinking',
                    'drinkin',
                    'shot',
                    'drunk',
                    'drank',
                    'alcohol',
                    'alcoholic',
                    'hangover',
                    'hungover',
                    'liquor',
                    'cocktail',
                    'booze',
                    'boozy',
                    'bottle',
                    'beer',
                    'cider',
                    'ale',
                    'tequila',
                    'vodka',
                    'wine',
                    'gin',
                    'whiskey',
                    'scotch',
                    'rum',
                    'bourbon',
                    'champagne',
                    'mojito',
                    'martini',
                    'daiquiri',
                    'jager',
                    'jagermeister',
                    'budweiser',
                    'miller',
                    'coors',
                    'heineken',
                    'bacardi',
                    'smirnoff',
                    'moet',
                    'hennesey',
                    'bar',
                    'pint',
                    'firewater',
                    'hootch',
                    'moonshine',
                    'spirits',
                    'swig',
                    'tipple',
                    'pub',
                    'margarita']


loveKeywords = ['love',
                'loving'
                'amorous',
                'romance',
                'passion',
                'romantic',
                'erotic',
                'kiss',
                'marry',
                'marriage',
                'babe',
                'honey',
                'heart',
                'darling',
                'baby',
                'babe'
                ]

violence = ['coercion', 'compulsion', 'constraint', 'duress', 'pressure', 'barbarity', 'brutality', 'savagery', 'damage', 'detriment', 'harm',
            'hurt', 'impairment', 'injury', 'crippling', 'maiming', 'mayhem', 'mutilation', 'assault', 'attack', 'bashing', 'battering', 'battery',
            'batting', 'beating', 'belting', 'bludgeoning', 'buffeting', 'clubbing', 'cudgeling(orcudgelling)', 'drubbing', 'flogging', 'hammering',
            'lacing', 'licking', 'mauling', 'paddling', 'pelting', 'pommeling', 'pounding', 'pummeling', 'smashing',
            'socking', 'thrashing', 'thumping', 'tromping', 'walloping', 'whaling', 'whipping', 'frenzy', 'fury', 'onslaught', 'outbreak', 'outrage',
            'paroxysm', 'rage', 'rampage', 'revolt', 'riot', 'rupture', 'shock', 'storm', 'terror', 'threat', 'tumult', 'turbulence', 'upheaval', 'uproar',
            'browbeating', 'bulldozing', 'bullying', 'hectoring', 'strong-arming', 'kill', 'fight', 'blowup', 'bullet','gun',
            'war', 'prison', 'bloody']


drug_smoking = ['smoke',
                'smoking',
                'cigarette',
                'drug',
                'drugs',
                'dose',
                'joint',
                'cannabis',
                'morphine',
                'heroin',
                'LSD',
                'cocaine'
                'high',
                'dope',
                'dose',
                'narco',
                'narcotic',
                'sedative',
                'poison',
                'doping',
                'abuse']

sex = ['sex',
       'sexual',
       'sexy',
       'fuck',
       'fucking',
       'fuckin',
       'dick',
       'pussy',
       'freeki',
       'freek',
       'nasty',
       'erotic',
       'suck',
       'porn',
       'vagina'
       ]


money_power = ['money',
         'rich',
         'gold',
         'cash',
         'dollar',
         'pay',
         'fortune',
         'wealth',
         'expensive',
         'luxury',
          'king',
        'kingdom',
           'power',
               'famous',
               'celebrity',
            'queens',
               'queen'
               ]


car = ['car', 'auto', 'drive', 'driving', 'racing']

